apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: hnmishra/expiration
          env:
            - name: NATS_URL #This is the key that will be used to connect to the nats service and must create a secret for this key
              value: 'http://nats-srv:4222' #This is the URL of the nats service
            - name: NATS_CLUSTER_ID #This is the key that will be used to connect to the nats service and must create a secret for this key
              value: 'ticketing' #This is the cluster id of the nats service
            - name: NATS_CLIENT_ID #This is the key that will be used to connect to the nats service and must create a secret for this key
              valueFrom: #This is the client id of the nats service
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_HOST #This is th e key that will be used to connect to the redis service and must create a secret for this key
              value: 'expiration-redis-srv' #This is the URL of the redis service

#service as not required as non of the services are exposed to the outside world

